### ISSUE TITLE
Module Futek missing

### ISSUE THREAD

**Issue by DataExplorerUser** [RavenLabsNH/DekaDynoGUI#3]
Hi Jeff,

I'm with the Dear PyGui team (discord_testpilot on Discord) and when I try to run DekaDynoGUI, the module "futek" appears to be missing, so the code cannot be executed. Now it does seem related to [this](https://github.com/RavenLabsNH/FutekTorqueTransducer), but I'm not quite sure how they fit together. I would love to try out DekaDynoGUI (or any other cool app you have created).

Thanks!

**Comment by jnelson614** [comment]
hi discord_testpilot,

This project is now dependent on OS and specific hardware (the futek stuff) and will also be incorporating more hardware as the project progresses. I fixed the issue and will try and keep the GUI running without the dependencies going forward.

**Comment by DataExplorerUser** [comment]
Hey,

It runs well now, so I could have a look at the app. It seems there might be another bug. I don't think it's worth the effort to look into it, so I'll close the issue.

Btw, if you are running exclusively on Windows, you could might be able to improve the font quality a bit.
